- run:
    name: Update GitOps repo
    command: |
      git clone https://github.com/abhishek-nm/gitops-config.git
      cd gitops-config/apps/hello-world

      echo "Before change:"
      cat values.yaml

      sed -i "s/^ *tag:.*/  tag: ${CIRCLE_SHA1}/" values.yaml

      echo "After change:"
      cat values.yaml

      git config user.email "ci@circleci"
      git config user.name "circleci"
      git add values.yaml
      git commit -m "hello-world → ${CIRCLE_SHA1}"
      git push
